import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/navbarWrapper";
import { Toaster } from "@/components/ui/sonner"
import FloatingBall from '@/components/instructionsBall'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DBOP March Madness",
  description: "Generated by a swaggy gent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <NavbarWrapper />    
  {children}    
  <Toaster />
  <FloatingBall />
      </body>
    </html>
  );
}